source 'https://github.com/CocoaPods/Specs.git'

target 'MDCategories', :exclusive => true do
  pod "MDCategories", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MDCategories", :path => "../"

  
end
